### ISSUE TITLE
unresolved dependency: com.typesafe.play.plugins#play-plugins-redis;2.3.1: not found

### ISSUE THREAD

**Issue by lagrz** [typesafehub/play-plugins#162]
I'm currently using activator and running into this issue with my Play project. My project is using scala 2.11.1 and sbt version 0.13.5, play framework version 2.3.8.

```
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"

resolvers += "google-sedis-fix" at "http://pk11-scratch.googlecode.com/svn/trunk/"

addSbtPlugin("com.typesafe.play.plugins" %% "play-plugins-redis" % "2.3.1")
```

```
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.typesafe.play.plugins#play-plugins-redis;2.3.1: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn] 		com.typesafe.play.plugins:play-plugins-redis:2.3.1 (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
sbt.ResolveException: unresolved dependency: com.typesafe.play.plugins#play-plugins-redis;2.3.1: not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:217)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:126)
	at sbt.IvyActions$$anonfun$update$1.apply(IvyActions.scala:125)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
	at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
	at sbt.IvySbt.withIvy(Ivy.scala:98)
	at sbt.IvySbt.withIvy(Ivy.scala:94)
	at sbt.IvySbt$Module.withModule(Ivy.scala:115)
	at sbt.IvyActions$.update(IvyActions.scala:125)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1223)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1221)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1244)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1242)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1246)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1241)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1249)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1214)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play.plugins#play-plugins-redis;2.3.1: not found
```

**Comment by jroper** [comment]
The redis plugin is not an sbt plugin, so it doesn't get added to your sbt plugins in `project/plugins.sbt`. It's a play library, so gets added to your `libraryDependencies` in `build.sbt`.

Read https://www.playframework.com/documentation/2.3.x/Build for more information on how to add dependencies and the structure of your build.

**Comment by lagrz** [comment]
Thanks for the clarification got it to work. :)
