### ISSUE TITLE
when play-redis to support play 2.6.x

### ISSUE THREAD

**Issue by ourgit** [typesafehub/play-plugins#178]
play-redis didnot work at play 2.6.x , do you have plan to support play 2.6.x?

**Comment by johdah** [comment]
@ourgit Are you getting the same error?

```
Exception in thread "main" java.lang.NoSuchMethodError: play.api.Logger$.info(Lscala/Function0;)V
| 	at com.typesafe.play.redis.JedisPoolProvider.get$lzycompute(JedisPoolProvider.scala:40)
| 	at com.typesafe.play.redis.JedisPoolProvider.get(JedisPoolProvider.scala:17)
| 	at com.typesafe.play.redis.JedisPoolProvider.get(JedisPoolProvider.scala:14)
| 	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
...
```

**Comment by gmethvin** [comment]
As stated in the readme, the plugins here are unsupported. You could try this redis plugin: https://github.com/KarelCemus/play-redis
