### ISSUE TITLE
JedisConnectionException: Could not get a resource from the pool

### ISSUE THREAD

**Issue by kishykumar** [typesafehub/play-plugins#181]
Hi,
I am using the Redis Plugin (with Jedis) for my Play framework project ([baasbox](https://github.com/baasbox/baasbox/tree/1.0.0-Final)). The plugin seems to be setup correctly: 

My application.log shows that the plugin is enabled: 
```
[info] - Redis Plugin enabled. Connecting to Redis on localhost:6379 to 0 with timeout 2000. 
[info] - Redis Plugin pool configuration: redis.clients.jedis.JedisPoolConfig@4d24e4d2[maxIdle=8,minIdle=0,maxActive=8,maxWait=-1,whenExhaustedAction=0,testOnBorrow=false,testOnReturn=false,testWhileIdle=true,timeBetweenEvictionRunsMillis=30000,numTestsPerEvictionRun=-1,minEvictableIdleTimeMillis=60000,softMinEvictableIdleTimeMillis=-1,lifo=true]
```

But, Cache.set throws the following exception: 
```
Wrapped by: redis.clients.jedis.exceptions.JedisConnectionException: Could not get a resource from the pool
	at redis.clients.util.Pool.getResource(Pool.java:22) ~[jedis-2.1.0.jar:na]
	at org.sedis.Pool.withJedisClient(sedis.scala:79) ~[sedis_2.10.0-1.1.1.jar:na]
	at com.typesafe.plugin.RedisPlugin$$anon$1.set_(RedisPlugin.scala:150) ~[play-plugins-redis_2.10-2.2.1.jar:2.2.1]
	at com.typesafe.plugin.RedisPlugin$$anon$1.set(RedisPlugin.scala:109) ~[play-plugins-redis_2.10-2.2.1.jar:2.2.1]
	at play.api.cache.Cache$.set(Cache.scala:58) ~[play-cache_2.10.jar:2.2.4]
	at play.api.cache.Cache.set(Cache.scala) ~[play-cache_2.10.jar:2.2.4]
	at play.cache.Cache.set(Cache.java:52) ~[play-cache_2.10.jar:2.2.4]
	at com.baasbox.security.SessionTokenProviderRedis.setSession(SessionTokenProviderRedis.java:103) ~[classes/:na]
```

Here's my configuration: 

> #application.conf: 
> redisplugin=enabled
> ehcacheplugin=disabled

play 2.2.4 built with Scala 2.10.3 (running Java 1.8.0_25)

```
val appDependencies = Seq(
"com.typesafe" %% "play-plugins-redis" % "2.2.1"
)

resolvers := Seq(
"Sedis Repo" at "http://pk11-scratch.googlecode.com/svn/trunk"
)
```

Seems like redis server is not even running! 
```
$ redis-cli
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```

I am sure I am missing something in my config. Can anybody please help here? I am stuck badly at this.

**Comment by kishykumar** [comment]
Figured out that the app doesn't start Redis database server by itself - you have to do it yourself manually! Sorry about that.
